import type { Member } from "@/types/member";

export const MEMBERS: Member[] = [
  {
    id: "mbr-001",
    nom: "Kouassi Aya",
    contact: "+225 07 12 34 56 78",
    type: "Membre",
    status: "Actif",
    date: "12 janv. 2024",
    avatarUrl: "/assets/images/avatar/avatar-1.jpg",
  },
  {
    id: "mbr-002",
    nom: "Traoré Ibrahim",
    contact: "treasurer@cie.club",
    type: "Bureau",
    status: "Actif",
    date: "5 mars 2023",
    avatarUrl: "/assets/images/avatar/avatar-2.jpg",
  },
  {
    id: "mbr-003",
    nom: "Partenaire Orange CI",
    contact: "partenariats@orange.ci",
    type: "Partenaire",
    status: "Actif",
    date: "18 sept. 2023",
    avatarUrl: "/assets/images/avatar/avatar-3.jpg",
  },
  {
    id: "mbr-004",
    nom: "Koné Mariam",
    contact: "+225 05 98 76 54 32",
    type: "Membre",
    status: "Inactif",
    date: "22 avr. 2026",
    avatarUrl: "/assets/images/avatar/avatar-4.jpg",
  },
  {
    id: "mbr-005",
    nom: "Diabaté Yao",
    contact: "sg@cie.club",
    type: "Bureau",
    status: "Actif",
    date: "10 juin 2022",
    avatarUrl: "/assets/images/avatar/avatar-5.jpg",
  },
  {
    id: "mbr-006",
    nom: "Jean-Paul N'Dri",
    contact: "jp.ndri@mail.ci",
    type: "Visiteur",
    status: "Actif",
    date: "3 mai 2026",
    avatarUrl: "/assets/images/avatar/avatar-6.jpg",
  },
  {
    id: "mbr-007",
    nom: "Soro Aminata",
    contact: "+225 01 23 45 67 89",
    type: "Membre",
    status: "Inactif",
    date: "14 fév. 2025",
    avatarUrl: "/assets/images/avatar/avatar-7.jpg",
  },
  {
    id: "mbr-008",
    nom: "Bamba Luc",
    contact: "luc.bamba@mail.ci",
    type: "Membre",
    status: "Actif",
    date: "8 nov. 2024",
    avatarUrl: "/assets/images/avatar/avatar-8.jpg",
  },
  {
    id: "mbr-009",
    nom: "Agence Com'Plus",
    contact: "contact@complus.ci",
    type: "Partenaire",
    status: "Inactif",
    date: "20 déc. 2022",
    avatarUrl: "/assets/images/avatar/avatar-9.jpg",
  },
  {
    id: "mbr-010",
    nom: "Coulibaly N'Guessan",
    contact: "digital@cie.club",
    type: "Bureau",
    status: "Actif",
    date: "1 juil. 2024",
    avatarUrl: "/assets/images/avatar/avatar-10.jpg",
  },
];
